format_version: 2
pipelines:
  "cinemas-ui":
    group: just-cinemas
    materials:
      cinemas-ui:
        git: "https://github.com/tw-avengers-bootcamp/bootcamp-just-cinemas-ui.git"
    stages:
      - lint:
          jobs:
            lint:
              resources:
                - node
              tasks:
                - script: |
                    yarn install
                    yarn lint
      - test:
          jobs:
            test:
              resources:
                - node
              tasks:
                - script: |
                    yarn install
                    yarn test_with_coverage
      - build:
          jobs:
            build:
              artifacts:
                - build:
                    source: build
                    destination: dist
              resources:
                - node
              tasks:
                - script: |
                    yarn install
                    yarn build
