version: '2'

services:
  agent-nodejs:
    image: jskswamy/gocd-agent-debian8-nodejs9.4:v17.12.0
    depends_on:
      - server
    environment:
      GO_SERVER_URL: https://server:8154/go
      AGENT_AUTO_REGISTER_KEY: 079e578b-87cc-46c9-9ab5-88997fc7ac59
      AGENT_AUTO_REGISTER_RESOURCES: node
      AGENT_AUTO_REGISTER_ENVIRONMENTS: ci
    volumes:
      - $PWD/.ssh:/home/go/.ssh

  agent-java:
    image: jskswamy/gocd-agent-debian-8-java:v17.12.0
    depends_on:
      - server
    environment:
      GO_SERVER_URL: https://server:8154/go
      AGENT_AUTO_REGISTER_KEY: 079e578b-87cc-46c9-9ab5-88997fc7ac59
      AGENT_AUTO_REGISTER_RESOURCES: java
      AGENT_AUTO_REGISTER_ENVIRONMENTS: ci
    volumes:
      - $PWD/.ssh:/home/go/.ssh

  server:
    image: gocd/gocd-server:v17.12.0
    volumes:
      - $PWD/godata:/godata
      - $PWD/.ssh:/home/go/.ssh
    ports:
      - "8153:8153"
      - "8154:8154"
  db:
    image: postgres:9.6.6
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
